# Nama workflow yang akan tampil di tab "Actions" GitHub
name: Deploy to GitHub Pages

# Pemicu (Trigger)
on:
  # 1. Menjalankan workflow setiap kali ada 'push' ke branch 'main'
  push:
    branches: [ "main" ]
  
  # 2. Memungkinkan Anda menjalankan workflow ini secara manual dari tab Actions
  workflow_dispatch:

# Mengatur izin untuk GITHUB_TOKEN agar workflow bisa mendeploy ke GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Mengatur agar hanya satu deployment yang berjalan sekaligus
concurrency:
  group: "pages"
  cancel-in-progress: true

# Daftar 'jobs' (pekerjaan) yang akan dijalankan
jobs:
  # Hanya ada satu job, yaitu 'deploy'
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest # Menggunakan runner Ubuntu versi terbaru
    
    steps:
      # Langkah 1: Mengunduh kode dari repository Anda
      - name: Checkout
        uses: actions/checkout@v4

      # Langkah 2: Mengkonfigurasi GitHub Pages
      - name: Setup Pages
        uses: actions/configure-pages@v5

      # Langkah 3: "Membangun" situs. Untuk situs statis, 
      # kita hanya perlu mengunggah semua file (.,) sebagai artefak.
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Unggah seluruh isi repository (karena index.html ada di root)
          path: '.' 

      # Langkah 4: Mendeploy artefak yang sudah diunggah ke GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4